### ISSUE TITLE
How to save your model?

### ISSUE THREAD

**Issue by FuShengRuoXian** [xkeeja/anomaly-detection-screws#1]
ae = AutoEncoder(encoder, decoder)
ae.compile(optimizer=Adam(learning_rate=0.001))
history = ae.fit(ds_train, epochs=1, verbose=200, validation_data=ds_val,callbacks=callbacks_list)
ae.save('model_weight.h5')

 raise NotImplementedError(
NotImplementedError: Saving the model to HDF5 format requires the model to be a Functional model or a Sequential model. It does not work for subclassed models, because such models are defined via the body of a Python method, which isn't safely serializable. Consider saving to the Tensorflow SavedModel format (by setting save_format="tf") or using `save_weight…

How to save your model after trainning correctly? Thanks a lot.

**Comment by xkeeja** [comment]
Saving the model directly doesn't work with this custom class, but you can use save_weights:
`ae.save_weights('model_weight.h5')`
